variables:
  GIT_STRATEGY: clone

stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - cd /home/bitrix/ext_www/api.bsi.local
    - php artisan test
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - ls -la /home/bitrix/ext_www/api.bsi.local/app/Modules/SED/*